### ISSUE TITLE
Support of TTGO T-Display

### ISSUE THREAD

**Issue by Avamander** [adafruit/Adafruit-ST7735-Library#109]
Just wanted to mention that the library nicely works with the TTGO T-Display ESP32 module with this config:
```c++
#define TFT_MOSI 19
#define TFT_SCLK 18
#define TFT_CS 5
#define TFT_DC 16
#define TFT_RST 23
#define TFT_BL 4
```

and

```c++
Adafruit_ST7789 tft = Adafruit_ST7789(TFT_CS, TFT_DC, TFT_MOSI, TFT_SCLK, TFT_RST);
```

```c++
tft.init(135, 240);           // Init ST7789 240x135
```

And in order to turn on backlight, set TFT_BL to HIGH.

Other tutorials suggested using other libraries and other code, but Adafruit's library seems to work better. 

Maybe some documentation could also mention it's usable on the ESP32?

**Comment by ladyada** [comment]
sounds great! thanks for the report :)
