### ISSUE TITLE
with custome fonts the background of the text doesn't clear

### ISSUE THREAD

**Issue by hamed-ta** [adafruit/Adafruit-ST7735-Library#116]
by using custome fonts in Adafruit_ST7789 library the background of the text doesn't clear even by using 

  tft.setTextColor(ST77XX_WHITE,ST77XX_BLACK);

  Micro is Atmega 644

![01](https://user-images.githubusercontent.com/9883945/77233479-4941cd80-6bc5-11ea-986d-48925809f8a2.png)
![02](https://user-images.githubusercontent.com/9883945/77233480-4cd55480-6bc5-11ea-8b2c-7456b0f250a8.png)

![WhatsApp Image 2020-03-21 at 22 43 20](https://user-images.githubusercontent.com/9883945/77233494-62e31500-6bc5-11ea-9509-6bfc3b082812.jpeg)

**Comment by PaintYourDragon** [comment]
This is on purpose and by design. It’s documented in the GFX guide:
https://learn.adafruit.com/adafruit-gfx-graphics-library/using-fonts#using-gfx-fonts-in-arduino-sketches-5-6

**Comment by hamed-ta** [comment]
so it's better to add the needed code to the library to replace the background of the custom fonts as well as the classic.
