### ISSUE TITLE
Strange offset when using a ST7789V

### ISSUE THREAD

**Issue by T94T** [adafruit/Adafruit-ST7735-Library#139]
We got a ST7789V display to work reasonably well with this library.
But in use with `tft.init(135, 240);` there is an offset:
<img width="186" alt="grafik" src="https://user-images.githubusercontent.com/17198363/113268248-798f7200-92d7-11eb-9e85-3e381cf84799.png">

For example, if we use `tft.init(240, 280);` we get this result:
<img width="152" alt="grafik" src="https://user-images.githubusercontent.com/17198363/113268284-8318da00-92d7-11eb-843d-229a278e21df.png">

**Comment by makermelissa** [comment]
Hmm, is that a different brand? If so, it looks like they are using different offsets than the Adafruit ones even with the same screen size, so we may have to come up with a slightly different solution than just looking at size.

**Comment by ladyada** [comment]
@T94T please submit a PR for your display when you get it working!
