### ISSUE TITLE
Flickering and using buffer

### ISSUE THREAD

**Issue by ChSt98** [adafruit/Adafruit-ST7735-Library#141]
Im using an 1.8inch ST7735 TFT display over SPI and im getting flickering when writing to the display due to having to black the whole screen when updating. 
Is there an ability to use a buffer like in many OLED display libraries? As the OLED displays seem to not have any flicker when updating.

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit-GFX-Library/blob/master/Adafruit_GFX.cpp#L2385
