### ISSUE TITLE
The 1.14" 135x240 display doesn't render properly in v1.8.2

### ISSUE THREAD

**Issue by kevinfrei** [adafruit/Adafruit-ST7735-Library#165]
PR #160 fixed one orientation, but broke another for the 135x240 ST7789 display: The offsets are wrong, so there's always some part of the screen that doesn't get drawn properly in rotations 0 (default) & 2. Here's a [video](https://1drv.ms/v/s!Ap9iqQ7FiN9QhtlsDZqWdKISrNAaIQ) that shows the problem. Here's [the sketch](https://github.com/kevinfrei/ST7789_135_240_test/blob/main/test.cpp) necessary to repro the issue. PR #162 is the fix. I've validated that the 320x240 screen still works properly, and if you look at the code, it's clear that my changes only affect the 135x240 screen.

Please hit me up if you need anything else.

**Comment by makermelissa** [comment]
Fixed via #162.
