### ISSUE TITLE
multiple displays

### ISSUE THREAD

**Issue by altermontrealiste** [adafruit/Adafruit-ST7735-Library#30]
Hi ; I would like to have many st7735 tft screens in my project and was wondering how I could do it (with spi)...

I figure the clk, miso and mosi could be on the same pin, cs would not... don't know for the others

Has multiple instanciation of the tft object been tried?

thanks

**Comment by PaintYourDragon** [comment]
Yes, just requires a separate CS line for each display and a little tomfoolery in the sketch. You can see this in action in the 'Uncanny Eyes' project:
https://learn.adafruit.com/animated-electronic-eyes-using-teensy-3-1/overview
