### ISSUE TITLE
Can't use ports 11, 12, 13 ?

### ISSUE THREAD

**Issue by elik745i** [adafruit/Adafruit-ST7735-Library#31]
If I use option 2, such as:

Adafruit_ST7735 tft = Adafruit_ST7735(TFT_CS, TFT_DC, TFT_MOSI, TFT_SCLK, TFT_RST);

I can't use pins 11, 12, 13 for some reason...how to solve?

**Comment by ladyada** [comment]
cant reproduce - seems to work just fine?
