### ISSUE TITLE
Is there any interest in supporting Deek Robot TFT Esplora compatible module?

### ISSUE THREAD

**Issue by davidkwast** [adafruit/Adafruit-ST7735-Library#40]
Hi. I did some modifications to calibrate the zero position and colors. It mixes the color of the blacktab with colstart/rowstart of the greentab. I am still doing some better tests, because this is my first experience with TFT LCD and Anduino.

If you are interested, I can do a proper pull request.

If it really works without any consequences, I will fork it anyway.

---

void Adafruit_ST7735::initR(uint8_t options) {
...
} else if(options == INITR_DEEKROBOT) {
    commandList(Rcmd2red);
    colstart = 2;
    rowstart = 1;
...
  // if black, change MADCTL color filter
  if ((options == INITR_BLACKTAB) || (options == INITR_MINI160x80) || (options == INITR_DEEKROBOT)) {
    writecommand(ST7735_MADCTL);
    writedata(0xC0);
  }

**Comment by davidkwast** [comment]
You can see the test code and some photos of the modulo bellow:

https://github.com/davidkwast/Adafruit-ST7735-Library/blob/master/test.ino
https://github.com/davidkwast/Adafruit-ST7735-Library/blob/master/deekrobot_blacktab.jpg
https://github.com/davidkwast/Adafruit-ST7735-Library/blob/master/deekrobot_fix.jpg
https://github.com/davidkwast/Adafruit-ST7735-Library/blob/master/deekrobot_back.jpg

**Comment by makermelissa** [comment]
Hi, thank you. It appears the scope of this is covered by using INIT_GREENTAB and using graphicstest.
