### ISSUE TITLE
esp8266 st7735 80x160 regression to gfx 1.2.5

### ISSUE THREAD

**Issue by tablatronix** [adafruit/Adafruit-ST7735-Library#50]
esp8266 latest stable

had to roll back gfx lib to 1.2.5

symtoms
blank screen no crash or errors with
graphicstest example.

Looking at diffs...

**Comment by ladyada** [comment]
thanx we did a big & much-needed refactor - lemme know if you find something!

**Comment by tablatronix** [comment]
https://github.com/adafruit/Adafruit-GFX-Library/pull/169

**Comment by tablatronix** [comment]
Not sure if USE_FAST_PINIO was supposed to be working for esp or not, but I do not think it works, and has always been disabled until 1.2.6 via include order

**Comment by ladyada** [comment]
ok does it work now?

**Comment by tablatronix** [comment]
Yes graphicstest works now on my st7735 on nodemcu v2 with just that change.

**Comment by tablatronix** [comment]
I have no other displays atm, I have ssd1306 at home though, I can check it later

**Comment by ladyada** [comment]
closing cause it seems this is resolved, reopen if not! :)
