### ISSUE TITLE
drawBMP issue with ST7735 library later than 1.1.0

### ISSUE THREAD

**Issue by srbonham** [adafruit/Adafruit-ST7735-Library#60]
- Arduino board:  Arduino Uno

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.7

Using the spitbmp example with the most recent ST7753 library no longer works correctly.  Only the top 20 or so pixels of the bmp go on the screen.  Additionally, if you use rotation, no BMP at all is displayed.  It's like the working canvas of the screen is only the top, even though HEIGHT and WIDTH show 160x128 respectfully.  

Reverting back to 1.1.0 allowed the spitbmp to work and my code works again.

Hardware is Arduino Uno + Adafruit 1.8 TFT  160x128 breakout with Micro SD

**Comment by ladyada** [comment]
what exact hardware are you using

**Comment by srbonham** [comment]
I am using this on the Adafruit 1.8 TFT  160x128 breakout with Micro SD

**Comment by PaintYourDragon** [comment]
Verify you have both the latest ST7735 and GFX libraries (1.2.4 and 1.3 respectively) installed.
Try the different init flags (INITR_GREENTAB, INITR_REDTAB, INITR_BLACKTAB) and see if any change in behavior.
Tested working on a canonical Arduino Uno and green-tabbed ST7735 breakout with SD (only rotations 0 and 2 work with that example, rotations 1 and 3 are scrambled, but that's a limitation of the spitftbitmap example code and not the library).

**Comment by PaintYourDragon** [comment]
If everything else checks out and running latest libraries, try slowing down the SPI rate, near the top of Adafruit_ST77xx.cpp:
`#define SPI_DEFAULT_FREQ         16000000      ///< Default SPI data clock frequency`
Try 8 MHz or even 4 MHz, see if any change.

**Comment by srbonham** [comment]
Thanks for your suggestions.

So i went back and verified that I was using the latest libraries.  I went with the latest GFX 1.3.1 and ST7735 1.2.4.   Interesting enough, the parrot.bmp is printing fine with setRotation on 0 and 2, but with 1 and 3 it is scrambled.  My BMP that used to work does not work.  Ive attached that bmp.

I also tried to use INITR_GREENTAB, INITR_REDTACK, and INITR_BLACKTAB respectfully.  No change.

I went through each version, 1.0.0, 1.0.1, 1.0.4, 1.0.6, 1.1.0, and starting 1.2.0 my bmp no longer prints without scrambling.  I changed `#define SPI_DEFAULT_FREQ 16000000 ///< Default SPI data clock frequency` to recommended 8 and 4mhz with no change.  Screen shots attached:

**Comment by srbonham** [comment]
[s4black.zip](https://github.com/adafruit/Adafruit-ST7735-Library/files/2568850/s4black.zip)

**Comment by srbonham** [comment]
This is example with v1.1.0, Both parrot and s4black bmp files are working correctly, all four rotation constants.

![img_1749](https://user-images.githubusercontent.com/23438049/48306936-6619bb80-e510-11e8-801e-1138c5837807.JPG)
![img_1750](https://user-images.githubusercontent.com/23438049/48306937-6619bb80-e510-11e8-8201-e743e2546914.JPG)

**Comment by srbonham** [comment]
That sounds great. In the meantime I will try the example code you’ve suggested and report back. Thanks a lot

Shawn

**Comment by PaintYourDragon** [comment]
Adafruit_ImageReader library is up and running
https://learn.adafruit.com/adafruit-gfx-graphics-library/loading-images
