### ISSUE TITLE
selectable hardware SPI for M0

### ISSUE THREAD

**Issue by orhanyor** [adafruit/Adafruit-ST7735-Library#63]
hey guys tried forums but couldnt get an answer. so im using feather m0 and trying to use additional hardware spi pins for st 7735 display. so far followed this tutorial here https://learn.adafruit.com/using-atsamd21-sercom-to-add-more-spi-i2c-serial-ports/creating-a-new-spi but couldnt figure out the proper constructor for the 0.96 display with custom spi pins.
here https://github.com/adafruit/Adafruit-ST7735-Library/blob/master/Adafruit_ST7735.cpp you can define selectable hardware SPI for ESP8266 but can anybody help me for the feather M0?

**Comment by ladyada** [comment]
yep this one 
https://github.com/adafruit/Adafruit-ST7735-Library/blob/master/Adafruit_ST7735.cpp#L36
is just fine, if the SPI device exists pass it in :)
