### ISSUE TITLE
ST7789 Compatibility issues with Teensy 3.2

### ISSUE THREAD

**Issue by tcottle** [adafruit/Adafruit-ST7735-Library#64]
- Arduino board:  Teensy 3.2

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.9

- example code graphicstest.ino results in a black display on Adafruit 3787 1.54" 240x240 Wide Angle TFT LCD Display with MicroSD - ST7789 on library versions 1.26 or later (works on 1.25)

A small delay, around 10uS, needs to be added between SPI_CS_HIGH() and SPI_CS_LOW() in the displayInit method to account for the fast IO speed in the Teensy series

Background on the issue can be found here:  https://forum.pjrc.com/threads/55317-New-adafruit-GFX-1-4-x-libs-doesn-t-work-for-me?p=202762&viewfull=1#post202762

**Comment by makermelissa** [comment]
This might fix the issue here as well: https://forums.adafruit.com/viewtopic.php?f=25&t=149351
