### ISSUE TITLE
ESP32 ST7735 change SPI pins not working

### ISSUE THREAD

**Issue by spilz87** [adafruit/Adafruit-ST7735-Library#65]
- Arduino board:  **ESP32**

- Arduino IDE version (found in Arduino -> About Arduino menu):  **1.9.0 beta**

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): **LIST REPRO STEPS BELOW**

I'm using this Library on an ESP32 with a lcd ST7735. it works well with default SPI pins 
(SPI_SCK->18, SPI_MOSI->23, SPI_MISO->19 and other pins : TFT_CS->15 ;TFT_RST->4; TFT_DC->27)

but when I try to change the SPI pins, it doesn't work anymore 
(SPI_SCK->36, SPI_MOSI->34, SPI_MISO->19 and other pins : TFT_CS->26 ;TFT_RST->32; TFT_DC->33)

I tryed to use this : 
Adafruit_ST7735 tft = Adafruit_ST7735(TFT_CS, TFT_DC, SPI_MOSI, SPI_SCK, TFT_RST);
but still not work.

is there an other way to change pin ?
maybe by forcing software SPI ?

thanks

**Comment by ladyada** [comment]
hiya some ESP32 pins are not IO but only input? you can try software SPI for sure just pass in those pins. we know that this works with alternate SPI objects on other chips. if you get more info you can re-open issue
