### ISSUE TITLE
1.3 ST7789 doesnt work after 1.2.5 release.

### ISSUE THREAD

**Issue by orhanyor** [adafruit/Adafruit-ST7735-Library#72]
Hello, wanted to report an issue with st7789 library. i tried to run it for the first time with my feather m0 and i had a blank screen i thought my display is the issue but downgrading the st7735/89 library to version to 1.2.5 made it work like a charm any other version after that like 1.2.6.. etc gives a blank screen.

**Comment by ladyada** [comment]
which display is this?

**Comment by orhanyor** [comment]
its the cheapo 240x240 chinese version, may be its not compatible but its interesting that it works up until 1.2.5

**Comment by ladyada** [comment]
@makermelissa please check our 240x240 ST7789, see if it still works?

**Comment by orhanyor** [comment]
by the way the code i tried is the graphicstest.ino from the library

**Comment by makermelissa** [comment]
Ok, thanks. I'll try that one out when I get back.

**Comment by makermelissa** [comment]
Thanks for reporting this. I was able to reproduce this.

**Comment by makermelissa** [comment]
I think this issue may be related to #64.

**Comment by orhanyor** [comment]
yes, seems like the same issue  thank you for your time :)
