### ISSUE TITLE
fix compiler's warnings for color

### ISSUE THREAD

**Issue by JM-FRANCE** [adafruit/Adafruit-ST7735-Library#80]
color type In the Adafruit ST7735 Library examples such as [graphicstest.ino](https://github.com/adafruit/Adafruit-ST7735-Library/blob/075609ce4684301392ca932528c58b96f8c80247/examples/graphicstest/graphicstest.ino#L260) the color is defined as an int instead of uint16_t

(same applies [line 277](https://github.com/adafruit/Adafruit-ST7735-Library/blob/075609ce4684301392ca932528c58b96f8c80247/examples/graphicstest/graphicstest.ino#L277))

**Comment by ladyada** [comment]
thanks, please submit PRs for these little fixes :)

**Comment by 2bndy5** [comment]
Seems to have been addressed in #97

**Comment by JM-FRANCE** [comment]
Thanks
