### ISSUE TITLE
Wemos D1 mini pro / TFT shield 1.4 v1.0.0 library compiling issue on arduino IDE

### ISSUE THREAD

**Issue by ManuHallais** [adafruit/Adafruit-ST7735-Library#82]
Wemos D1 mini pro / TFT shield 1.4 v1.0.0 library compiling issue on arduino IDE
I had no problem with the esp but when it comes to compile using the gfx and st7735 lib, nothing compiles.

I've tried to compile the examples but I have a problem with :
Adafruit_ST7735.cpp: In member function 'void Adafruit_ST7735::initR(uint8_t)'
Adafruit_ST7735.cpp: In member function 'virtual void Adafruit_ST7735::setRotation(uint8_t)':

All sort of problem with them. 
Do I have to downgrade the library ? It seems to work a year ago...
http://www.esp8266learning.com/wemos-1-44-inch-tft-lcd-shield-examples.php

**Comment by makermelissa** [comment]
Hi, could you be more specific as to the error message? Thanks

**Comment by ManuHallais** [comment]
ok so I tried this code : https://github.com/wemos/D1_mini_Examples/blob/master/examples/04.Shields/TFT_1.4_Shield/simple/simple.ino

And there's my error message : 
`C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST7735.cpp: In member function 'void Adafruit_ST7735::initR(uint8_t)':

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST7735.cpp:244:40: error: 'sendCommand' was not declared in this scope

     sendCommand(ST77XX_MADCTL, &data, 1);

                                        ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST7735.cpp: In member function 'virtual void Adafruit_ST7735::setRotation(uint8_t)':

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST7735.cpp:294:6: error: '_xstart' was not declared in this scope

      _xstart   = _colstart;

      ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST7735.cpp:295:6: error: '_ystart' was not declared in this scope

      _ystart   = _rowstart;

      ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST7735.cpp:359:40: error: 'sendCommand' was not declared in this scope

   sendCommand(ST77XX_MADCTL, &madctl, 1);

                                        ^

Plusieurs bibliothèque trouvées pour "Adafruit_GFX.h"
Utilisé : C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_GFX
Non utilisé : C:\Program Files (x86)\Arduino\libraries\Adafruit_GFX
Plusieurs bibliothèque trouvées pour "Adafruit_ST7735.h"
Utilisé : C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735
Non utilisé : C:\Program Files (x86)\Arduino\libraries\Adafruit_ST7735
Utilisation de la bibliothèque Adafruit_GFX version 1.2.2 dans le dossier: C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_GFX 
Utilisation de la bibliothèque Adafruit_ST7735 version 1.3.7 dans le dossier: C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735 
Utilisation de la bibliothèque SPI version 1.0 dans le dossier: C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\SPI 
exit status 1
C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.cpp: In member function 'void Adafruit_ST77xx::displayInit(const uint8_t*)':

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.cpp:103:35: error: 'sendCommand' was not declared in this scope

     sendCommand(cmd, addr, numArgs);

                                   ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.cpp: In member function 'virtual void Adafruit_ST77xx::begin(uint32_t)':

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.cpp:127:3: error: 'invertOnCommand' was not declared in this scope

   invertOnCommand  = ST77XX_INVON;

   ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.cpp:128:3: error: 'invertOffCommand' was not declared in this scope

   invertOffCommand = ST77XX_INVOFF;

   ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.cpp:130:24: error: no matching function for call to 'Adafruit_ST77xx::initSPI(uint32_t&, uint8_t&)'

   initSPI(freq, spiMode);

                        ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.cpp:130:24: note: candidate is:

In file included from C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.h:31:0,

                 from C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.cpp:25:

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_GFX/Adafruit_SPITFT.h:31:19: note: void Adafruit_SPITFT::initSPI(uint32_t)

         void      initSPI(uint32_t freq);

                   ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_GFX/Adafruit_SPITFT.h:31:19: note:   candidate expects 1 argument, 2 provided

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.cpp: In member function 'virtual void Adafruit_ST77xx::setAddrWindow(uint16_t, uint16_t, uint16_t, uint16_t)':

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.cpp:158:8: error: '_xstart' was not declared in this scope

   x += _xstart;

        ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.cpp:159:8: error: '_ystart' was not declared in this scope

   y += _ystart;

        ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.cpp: In member function 'virtual void Adafruit_ST77xx::setRotation(uint8_t)':

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.cpp:186:6: error: '_xstart' was not declared in this scope

      _xstart = _colstart;

      ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.cpp:187:6: error: '_ystart' was not declared in this scope

      _ystart = _rowstart;

      ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.cpp:206:40: error: 'sendCommand' was not declared in this scope

   sendCommand(ST77XX_MADCTL, &madctl, 1);

                                        ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.cpp: In member function 'void Adafruit_ST77xx::enableDisplay(boolean)':

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST77xx.cpp:229:54: error: 'sendCommand' was not declared in this scope

   sendCommand(enable ? ST77XX_DISPON : ST77XX_DISPOFF);

                                                      ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST7789.cpp: In member function 'void Adafruit_ST7789::init(uint16_t, uint16_t, uint8_t)':

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST7789.cpp:111:9: error: assignment of read-only member 'Adafruit_GFX::WIDTH'

   WIDTH = width;

         ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST7789.cpp:112:10: error: assignment of read-only member 'Adafruit_GFX::HEIGHT'

   HEIGHT = height;

          ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST7789.cpp: In member function 'virtual void Adafruit_ST7789::setRotation(uint8_t)':

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST7789.cpp:135:6: error: '_xstart' was not declared in this scope

      _xstart = _colstart;

      ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST7789.cpp:136:6: error: '_ystart' was not declared in this scope

      _ystart = _rowstart;

      ^

C:\Users\Emmanuel\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\Adafruit_ST7735\Adafruit_ST7789.cpp:163:40: error: 'sendCommand' was not declared in this scope

   sendCommand(ST77XX_MADCTL, &madctl, 1);

                                        ^

Erreur de compilation pour la carte LOLIN(WEMOS) D1 mini Pro `

**Comment by makermelissa** [comment]
According to the error message, you're only running Adafruit GFX version 1.2.2 and that needs to be updated. The latest version is 1.5.6.
