### ISSUE TITLE
Problem about color in ST7735

### ISSUE THREAD

**Issue by hznupeter** [adafruit/Adafruit-ST7735-Library#86]
- Arduino board:  **ESP32**

- Arduino IDE version:  **1.8.9**

I can use the ST7735 screen on ESP32 ,but only one problem is about the color.
whatever i change the color ,the display color is not the one  I code.

I have write a sketch based on https://github.com/adafruit/Adafruit-ST7735-Library/blob/master/examples/displayOnOffTest/displayOnOffTest.ino
I just left the simplest code, i set the background color is Blue,and the text color is yellow.
But the result is diffient as below,the background is RED,and the text seems WHITE.

I cant find the way ,please help,thank you!
![微信图片_20190807220256](https://user-images.githubusercontent.com/6317759/62629917-a18ecc80-b960-11e9-9c53-9e3603e17bb6.jpg)

code
```
#include <Adafruit_GFX.h>
#include <Adafruit_ST7735.h>
#include <SPI.h>
Adafruit_ST7735 tft = Adafruit_ST7735(TFT_CS, TFT_DC, TFT_MOSI, TFT_SCLK, -1);
const uint16_t  Display_Color_Black        = 0x0000;
const uint16_t  Display_Color_Blue         = 0x001F;
const uint16_t  Display_Color_Red          = 0xF800;
const uint16_t  Display_Color_Green        = 0x07E0;
const uint16_t  Display_Color_Cyan         = 0x07FF;
const uint16_t  Display_Color_Magenta      = 0xF81F;
const uint16_t  Display_Color_Yellow       = 0xFFE0;
const uint16_t  Display_Color_White        = 0xFFFF;
void setup() {
  tft.initR(INITR_144GREENTAB);
  tft.setFont();
  tft.fillScreen(Display_Color_Blue);
  tft.setTextColor(Display_Color_Yellow);
  tft.setTextSize(3);
  tft.setCursor(20, 20);
  tft.print("123456");
}
void loop() {
  delay(100);
}
```

**Comment by ladyada** [comment]
yeah you're using a knockoff display - not from adafruit, so colors are mixed. you'll need to redefine your colors to swap red and blue
