### ISSUE TITLE
Identifying three versions of ST7735 panels

### ISSUE THREAD

**Issue by ohporter** [adafruit/Adafruit-ST7735-Library#9]
I wrote the st7735fb Linux driver hosted at https://github.com/ohporter/linux-koen/commits/linux-ti33x-psp-3.2-r6c+gitr09e9651bcf2ee8d86685f2a8075bc6557b1d3b91-st7735fb back in the November timeframe from the tutorial code at the time. Recently somebody using the driver had problems that caused me to come back and see that we have two other breakout board versions now.

My issue is, how can we visually identify which one we have? I see the code mentioning ST7735R (green or red tab) and ST7735B. I'd like people to be able to select one of them visibly if the green or red tab refers to something.

From a photo sent to me, I see no identifying difference that would help people to choose which of the 3 variants. Any thoughts? I know from the code here that I have the "green tab" version so it would help to know what that means. R versus B is pretty clear at least, though I'm wishing that the PCB carried an identifying sticker so people know what they have. Any help is appreciated.

**Comment by dhrupal93** [comment]
What is the difference between ST7735R and ST7735S LCD modules?

**Comment by marcmerlin** [comment]
https://cdn-shop.adafruit.com/datasheets/ST7735R_V0.2.pdf
and
https://drive.google.com/drive/folders/1kZUh8Z9ixZ2sZOLjAbcSK9TWxPxOgN3E
I didn't read all the pages to spot the differences, but from testing, they are not fully identical in behaviour.
See  https://youtu.be/YwbfFoFp0ko and https://youtu.be/0-Fq1s2xQbM
But as I think adafruit pointed out, they do not sell ST7735S screen, so their driver doesn't have to support them, nor are they interested in providing support for hardware they didn't sell (and understandably so).
