### ISSUE TITLE
Recent change breaks rotation on 240x240 ST7789 displays

### ISSUE THREAD

**Issue by PaintYourDragon** [adafruit/Adafruit-ST7735-Library#90]
Something in the recent changes for 1.13" display support breaks rotation on 1.54" ST7789 displays (e.g. HalloWing M4, MONSTER M4SK). Everything is shifted up ~1/3 of screen. See rotationtest example or M4_Eyes sketch for symptoms.

**Comment by makermelissa** [comment]
Please check if #111 fixes this.

**Comment by makermelissa** [comment]
Ok, I just tried M4_Eyes and am not seeing the issue, so it was likely fixed by #111.
